# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# -----------------------------------------------------------------------------------------------
# Server
# -----------------------------------------------------------------------------------------------
server:
  servlet:
    context-path: /account-enquiry-service

  port: ${override.port:8080}

spring:
  datasource:
    url: jdbc:h2:mem:testdb
